-- premake-helpers.lua

function cleanGenerated()
    os.rmdir("core/bin")
    os.rmdir("core/obj")
    os.rmdir("toolkit/bin")
    os.rmdir("toolkit/obj")
    os.rmdir("example-game-1/bin")
    os.rmdir("example-game-1/obj")
    os.rmdir("example-sakura/bin")
    os.rmdir("example-sakura/obj")
    os.rmdir("vendor/cpptrace/bin")
    os.rmdir("vendor/cpptrace/obj")
    os.rmdir("vendor/libassert/bin")
    os.rmdir("vendor/libassert/obj")
    os.remove("**.sln")
    os.remove("**.vcxproj")
    os.remove("**.vcxproj.filters")
    os.remove("**.vcxproj.user")
    os.remove("**.vcxitems")
    os.remove("**.vcxitems.filters")
end